"use client";

import React from "react";
import { cn } from "@/lib/utils";

// Generated by UX Master Component Generator v4
// Timestamp: 2026-02-26T00:48:30.884527
// Source: https://templates.envytheme.com/fila/project-management.html

export interface InputProps {
  variant?: string;
  size?: string;
  disabled?: boolean;
  placeholder?: string;
  value?: string;
  onChange?: (value: string) => void;
}

export const Input = React.forwardRef<
  HTMLINPUTElement,
  InputProps
>((variant, size, disabled, placeholder, value, onChange, className, ...props}, ref) => {
  return (
    <INPUT
      ref={ref}
      className={cn(
        "flex h-10 w-full rounded-md border border-input bg-background px-3 py-2
        text-sm ring-offset-background
        placeholder:text-muted-foreground
        focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring
        disabled:cursor-not-allowed disabled:opacity-50",
        className
      )}}
      {...props}
    >
      {children}
    </INPUT>
  );
}});

Input.displayName = "Input";