"use client";

import React from "react";
import { cn } from "@/lib/utils";

// Generated by UX Master Component Generator v4
// Timestamp: 2026-02-26T00:48:30.884518
// Source: https://templates.envytheme.com/fila/project-management.html

export interface CardProps {
  variant?: string;
  padding?: string;
  children: React.ReactNode;
}

export const Card = React.forwardRef<
  HTMLDivElement,
  CardProps
>((variant, padding, children, className, ...props}, ref) => {
  return (
    <Div
      ref={ref}
      className={cn(
        "rounded-lg border bg-card text-card-foreground shadow-sm
        transition-shadow hover:shadow-md",
        className
      )}}
      {...props}
    >
      {children}
    </Div>
  );
}});

Card.displayName = "Card";