"use client";

import React from "react";
import { cn } from "@/lib/utils";

// Generated by UX Master Component Generator v4
// Timestamp: 2026-02-26T00:48:30.884499
// Source: https://templates.envytheme.com/fila/project-management.html

export interface ButtonProps {
  variant?: string;
  size?: string;
  disabled?: boolean;
  loading?: boolean;
  children: React.ReactNode;
}

export const Button = React.forwardRef<
  HTMLBUTTONElement,
  ButtonProps
>((variant, size, disabled, loading, children, className, ...props}, ref) => {
  return (
    <BUTTON
      ref={ref}
      className={cn(
        "inline-flex items-center justify-center
        font-medium transition-colors
        focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-offset-2
        disabled:pointer-events-none disabled:opacity-50"
        "  // Size: sm
          "h-8 px-3 text-sm": size === "sm",
          // Size: md (default)
          "h-10 px-4 text-base": size === "md",
          // Size: lg
          "h-12 px-6 text-lg": size === "lg",
          // Variant: primary
          "text-white hover:opacity-90": variant === "primary",
          // Variant: secondary
          "bg-secondary text-secondary-foreground hover:bg-secondary/90": variant === "secondary",
          // Variant: outline
          "border border-input bg-background hover:bg-accent hover:text-accent-foreground": variant === "outline",
          // Variant: ghost
          "hover:bg-accent hover:text-accent-foreground": variant === "ghost",,
        className
      )}}
      {...props}
    >
      {children}
    </BUTTON>
  );
}});

Button.displayName = "Button";