/**
 * Auto-generated by UX Master — Semi-Sync Harvester Protocol
 * Source: https://showcase.myharavan.com/admin/dashboard/generals
 * Title: Demo Haravan ~ Tổng quan ~ Haravan
 *
 * This component uses @douyinfe/semi-ui and inherits the
 * harvested theme via semi-theme-override.css.
 */
import React from 'react';
import { Layout, Nav, Button, Avatar, Dropdown, Card, Table, Tag, Badge, Descriptions, Typography, Row, Col } from '@douyinfe/semi-ui';
import { IconHome, IconUser, IconSetting, IconList, IconArrowUp, IconArrowDown, IconSearch, IconFilter } from '@douyinfe/semi-icons';
import './semi-theme-override.css';

const { Sider, Content, Header } = Layout;
const { Title, Text } = Typography;

const HaravanDashboard = () => {
    // KPI data
    const kpis = [
        { label: 'Doanh thu', value: '₫0', change: '0%', direction: 'neutral' },
        { label: 'Đơn hàng', value: '0', change: '0%', direction: 'neutral' },
        { label: 'Đơn chờ xử lý', value: '157', change: '', direction: 'warning' },
        { label: 'Đơn chờ giao', value: '81', change: '', direction: 'warning' },
    ];

    // Order table data
    const columns = [
        { title: 'Mã đơn', dataIndex: 'id', width: 100 },
        { title: 'Khách hàng', dataIndex: 'customer' },
        {
            title: 'Trạng thái',
            dataIndex: 'status',
            render: (text) => {
                const colorMap = { 'Hoàn thành': 'green', 'Chờ xử lý': 'orange', 'Đã hủy': 'red' };
                return <Tag color={colorMap[text] || 'blue'}>{text}</Tag>;
            },
        },
        { title: 'Tổng tiền', dataIndex: 'total', align: 'right' },
        { title: 'Ngày tạo', dataIndex: 'date' },
    ];

    const orders = [
        { key: '1', id: '#1001', customer: 'Nguyễn Văn A', status: 'Chờ xử lý', total: '₫450,000', date: '25/02/2026' },
        { key: '2', id: '#1002', customer: 'Trần Thị B', status: 'Hoàn thành', total: '₫1,200,000', date: '25/02/2026' },
        { key: '3', id: '#1003', customer: 'Lê Minh C', status: 'Đã hủy', total: '₫680,000', date: '24/02/2026' },
    ];

    return (
        <Layout style={{ height: '100vh' }}>
            <Sider style={{ width: 240, background: 'var(--semi-color-bg-2)' }}>
                <Nav
                    style={{ height: '100%' }}
                    defaultSelectedKeys={["overview"]}
                    items={[
                        { itemKey: 'overview', text: 'Tổng quan', icon: <IconHome /> },
                        { itemKey: 'orders', text: 'Đơn hàng', icon: <IconList /> },
                        { itemKey: 'customers', text: 'Khách hàng', icon: <IconUser /> },
                        { itemKey: 'settings', text: 'Cài đặt', icon: <IconSetting /> },
                    ]}
                    header={{ text: 'Demo Haravan', logo: <Avatar size="small" color="blue">H</Avatar> }}
                    footer={{ collapseButton: true }}
                />
            </Sider>
            <Layout>
                <Content style={{ padding: 24, background: 'var(--semi-color-bg-0)' }}>
                    {/* KPI Cards */}
                    <Row gutter={16} style={{ marginBottom: 24 }}>
                        {kpis.map((kpi, i) => (
                            <Col span={6} key={i}>
                                <Card style={{ borderRadius: 'var(--semi-border-radius-large)' }}>
                                    <Text type="secondary">{kpi.label}</Text>
                                    <Title heading={3} style={{ margin: '8px 0 0' }}>{kpi.value}</Title>
                                    {kpi.change && (
                                        <Text type="secondary" size="small">
                                            {kpi.direction === 'up' ? <IconArrowUp /> : <IconArrowDown />} {kpi.change}
                                        </Text>
                                    )}
                                </Card>
                            </Col>
                        ))}
                    </Row>

                    {/* Orders Table */}
                    <Card
                        title="Đơn hàng gần đây"
                        headerExtraContent={
                            <Button theme="solid" type="primary" icon={<IconSearch />}>Tìm kiếm</Button>
                        }
                        style={{ borderRadius: 'var(--semi-border-radius-large)' }}
                    >
                        <Table
                            columns={columns}
                            dataSource={orders}
                            pagination={{ pageSize: 10 }}
                        />
                    </Card>
                </Content>
            </Layout>
        </Layout>
    );
};

export default HaravanDashboard;
