import { VideoPlan } from './planner.js';
import { VideoScript, VideoFormat } from '../../src/lib/types';
import dotenv from 'dotenv';

dotenv.config();

export const scripterAgent = {
  async generateScript(
    plan: VideoPlan, 
    context: string, 
    format: VideoFormat = 'tiktok', 
    language: 'vi' | 'en' = 'vi'
  ): Promise<VideoScript> {
    console.log(`[Scripter] Writing JSON script for Remotion...`);
    
    const id = `video_${Date.now()}`;
    
    // If no OpenAI key, generate a hardcoded 12s script designed for CM AutoPilot demo
    if (!process.env.OPENAI_API_KEY || process.env.OPENAI_API_KEY === 'dummy') {
         console.log(`[Scripter] Fallback mode: Using pre-baked script for CM AutoPilot.`);
         return {
          id,
          title: "CM AutoPilot Demo",
          hook: plan.hook,
          hook_formula: plan.hookFormula,
          language,
          duration_target: 12,
          format,
          cta: plan.cta,
          hashtags: ["#vibecoding", "#cody", "#autopilot"],
          scenes: [
            { time_start: 0, duration: 4, text: plan.hook, visual: "TitleCard" },
            { time_start: 4, duration: 4, text: "Chỉ cần ra lệnh bằng tiếng Việt.", visual: "DarkTerminal", props: { command: "> Giới thiệu tôi CM AutoPilot" } },
            { time_start: 8, duration: 4, text: plan.cta, visual: "EndCard" }
          ],
          metadata: {
            ai_generated: true,
            ai_disclosure: "This is a fallback CM AutoPilot Local Demo."
          }
        };
    }
    
    // Stub implementation. In production, this would prompt OpenAI to generate the exact JSON structure.
    return {
      id,
      title: plan.idea,
      hook: plan.hook,
      hook_formula: plan.hookFormula,
      language,
      duration_target: 30,
      format,
      cta: plan.cta,
      hashtags: ["#vibecoding", "#ai", "#coding"],
      scenes: [
        { time_start: 0, duration: 3, text: plan.hook, visual: "TitleCard" },
        { time_start: 3, duration: 5, text: "Here is step 1.", visual: "VsCodeGlow", props: { code: "// step 1" } },
        { time_start: 8, duration: 4, text: "Here is step 2.", visual: "DarkTerminal", props: { command: "run magic" } },
        { time_start: 12, duration: 3, text: plan.cta, visual: "EndCard" }
      ],
      metadata: {
        ai_generated: true,
        ai_disclosure: "This video was fully generated by an AI pipeline."
      }
    };
  }
};
