"use client";

import React from "react";
import { cn } from "@/lib/utils";

// Generated by UX Master Component Generator v4
// Timestamp: 2026-02-26T00:48:30.884533
// Source: https://templates.envytheme.com/fila/project-management.html

export interface BadgeProps {
  variant?: string;
  children: React.ReactNode;
}

export const Badge = React.forwardRef<
  HTMLSPANElement,
  BadgeProps
>((variant, children, className, ...props}, ref) => {
  return (
    <SPAN
      ref={ref}
      className={cn(
        "inline-flex items-center rounded-full border px-2.5 py-0.5
        text-xs font-semibold transition-colors
        focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2",
        className
      )}}
      {...props}
    >
      {children}
    </SPAN>
  );
}});

Badge.displayName = "Badge";